# Generated by Django 6.0.3 on 2026-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIEMapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshark_path', models.CharField(default='', max_length=500)),
                ('nmap_path', models.CharField(default='', max_length=500)),
                ('interface', models.CharField(default='1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
